FROM nvcr.io/nvidia/pytorch:25.12-py3

RUN pip install --no-cache-dir \
    transformers==4.46.3  \
    tokenizers \
    PyMuPDF \
    img2pdf \
    einops \
    easydict \
    addict \
    Pillow \
    numpy \
    safetensors \
    accelerate \
    sentencepiece \
    qwen-vl-utils \
    huggingface_hub

WORKDIR /workspace

CMD ["/bin/bash"]
